spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    error:
      include-message: never
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false

app:
  security:
    cookie:
      secure: true