spring:
  datasource:
    url: ${DEV_DB_URL:jdbc:postgresql://localhost:5432/fourbagger}
    username: ${DEV_DB_USERNAME:postgres}
    password: ${DEV_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    cookie:
      secure: false
